name: Sprite Updates to Discord

on:
  push:
    paths:
      - 'sprites/gen5/**'
      - 'sprites/gen5-shiny/**'
      - 'sprites/gen5-back/**'
      - 'sprites/gen5-back-shiny/**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2   # important!

      - name: Collect changed files
        id: changes
        run: |
          echo "CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^(sprites/gen5|sprites/gen5-shiny|sprites/gen5-back|sprites/gen5-back-shiny)/' || true)" >> $GITHUB_ENV
          echo "Detected changes:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: Send update to Discord
        if: env.CHANGED != ''
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            📢 **Gen 5 sprite update detected!**
            Repo: ${{ github.repository }}
            Commit: [${{ github.sha }}](${{ github.event.head_commit.url }})
            Author: ${{ github.actor }}
            Message: ${{ github.event.head_commit.message }}

            Files changed:
            ```
            ${{ env.CHANGED }}
            ```
